### ISSUE TITLE
README file needs to be updated

### ISSUE THREAD

**Issue by noahaus** [salvadorlab/mbovpan#7]
self explanatory - should be easy to know how to install and use mbovpan

**Comment by noahaus** [comment]
Hey yall, could you do me a favor and try to run mbovpan using the instructions I have in the README file? I want to know what other information needs to be included 
@Ehsan-suez @rx32940

**Comment by Ehsan-suez** [comment]
<img width="599" alt="Screen Shot 2022-09-28 at 9 07 22 AM" src="https://user-images.githubusercontent.com/73665703/192786524-0b84376e-2976-4482-b299-df9b86e994b7.png">

Im getting this issue while trying to create the environment. (screenshot attached)

**Comment by rx32940** [comment]
![Screen Shot 2022-09-28 at 9 37 51 AM](https://user-images.githubusercontent.com/31255012/192793341-5eff13b9-db82-42e1-8172-749e3c70920e.png)

I was able to create the env, but saw this error when start running the pipeline

**Comment by noahaus** [comment]
Thank you both! 

@Ehsan-suez that is good to know, I will look at the mbovpan environment and make some changes. You ran this on the cluster, correct? 

@rx32940 this is a coding error on my end, thanks for catching it 

I will ask you to do this next monday as well - thanks for the help!

**Comment by noahaus** [comment]
I will need to check how the environment YAML works, since Ehsan had issue with it a while ago. Will check on my own system first

**Comment by noahaus** [comment]
I should create an example usages section.

**Comment by noahaus** [comment]
Added a few extra sections to this, and I'm content at the moment. Spending time on other things will be not really a good use of time?
